# Generated by Django 3.2.8 on 2021-12-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_bannersmall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bannersmall',
        ),
    ]
